name: Prod Auto Deploy Pipeline
on:
  release:
    types:
      - created
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy code
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Code deploy action step
        uses: ./gitrunner/ 
        id: deploy
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          commit_id: ${{ github.sha }}
          application_name: 'web-server'
